### ISSUE TITLE
个人作品和收藏作品功能页面

### ISSUE THREAD

**Issue by sodatodo** [nanxiaobei/taro-ux-kits#1]
想问问作者，个人作品和收藏作品这个页面的功能是怎么实现的，直观感觉Swiper是在tab之下的，但是切换的过程中好像是 swiper包括了整个页面，敢问怎么实现这么酷炫的效果，非常感谢

**Comment by nanxiaobei** [comment]
个人作品和收藏作品 Tab 切换是用 Swiper 实现的。

实际情况做了很多体验的优化，这块实现挺琐碎的。

是动态计算下面图片区域的高度，如果未填满剩余屏幕，就手动设置高度，去填满，填满了就不管了。

还有切换 Swiper 后，另一个 Tab 高度和滚动位置同步的问题。

总之就是保持两者的滚动位置一致，SwiperItem 动态填满了剩下的屏幕，这样就是整个页面可操作了。

**Comment by sodatodo** [comment]
那真实的Swiper组件应该占据什么位置，是整个页面，还是tab以下到屏幕以上这个区域

**Comment by nanxiaobei** [comment]
Tab 以下的区域，Tab 就是 Swiper 实现的。

**Comment by sodatodo** [comment]
从滚动条的长度来看，Swiper并不是固定高度，当SwiperItem发生切换的时候也要将Swiper调整至SwiperItem的高度么

**Comment by sodatodo** [comment]
噢 还可以这样66666

**Comment by sodatodo** [comment]
但是Swiper在通过setState调整高度的时候会导致重新渲染，滑动的状态又会丢失

**Comment by sodatodo** [comment]
啊...这个效果好复杂啊,大神能不能微信教教我啊 我微信fro1099

**Comment by nanxiaobei** [comment]
不会丢失滚动状态的。

**Comment by sodatodo** [comment]
我这里写了一个演示的demo，从高度比较高的SwiperItem往高度低的Item切换的时候就很奇怪
https://github.com/sodatodo/swiper-list
